"""Add UserProfile model

Revision ID: 62253157cdad
Revises: 5152f8a8419c
Create Date: 2024-12-07 21:48:52.896491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62253157cdad'
down_revision = '5152f8a8419c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('function', sa.VARCHAR(length=100), nullable=False),
    sa.Column('matricule', sa.VARCHAR(length=50), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('recruitment_date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('unit_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_worker_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('user_id', name='uq_worker_user_id')
    )
    # ### end Alembic commands ###
