"""Add Worker model

Revision ID: 6523c69373c5
Revises: 66bbd0eb0aee
Create Date: 2024-12-07 21:10:33.002750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6523c69373c5'
down_revision = '66bbd0eb0aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bilan_quotidien')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilan_quotidien',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('wilaya', sa.VARCHAR(length=50), nullable=False),
    sa.Column('commune', sa.VARCHAR(length=100), nullable=False),
    sa.Column('volume_produit', sa.FLOAT(), nullable=False),
    sa.Column('volume_distribue', sa.FLOAT(), nullable=False),
    sa.Column('taux_remplissage', sa.FLOAT(), nullable=False),
    sa.Column('nombre_abonnes', sa.INTEGER(), nullable=False),
    sa.Column('duree_distribution', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('unit_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('dotation', sa.FLOAT(), nullable=False),
    sa.Column('population_totale', sa.INTEGER(), nullable=False),
    sa.Column('population_desservie', sa.INTEGER(), nullable=False),
    sa.Column('taux_desserte', sa.FLOAT(), nullable=False),
    sa.Column('abonnes_touches', sa.INTEGER(), nullable=False),
    sa.Column('fuites_reparees', sa.INTEGER(), nullable=False),
    sa.Column('casses_reparees', sa.INTEGER(), nullable=False),
    sa.Column('fuites_signalees', sa.INTEGER(), nullable=False),
    sa.Column('casses_signalees', sa.INTEGER(), nullable=False),
    sa.Column('observations', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
