"""Make mesures_prises nullable and add date_resolution

Revision ID: 66bbd0eb0aee
Revises: 5025b65ef91d
Create Date: 2024-12-06 20:57:14.818233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bbd0eb0aee'
down_revision = '5025b65ef91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_resolution', sa.DateTime(), nullable=True))
        batch_op.alter_column('mesures_prises',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.alter_column('mesures_prises',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('date_resolution')

    # ### end Alembic commands ###
