"""Add BilanQuotidien model

Revision ID: 8abb78741d41
Revises: 186f8dedf4e2
Create Date: 2024-12-01 15:02:15.562415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abb78741d41'
down_revision = '186f8dedf4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
