""""add_unit_and_user_management"

Revision ID: cad30124c08d
Revises: 
Create Date: 2024-11-30 00:52:20.112140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad30124c08d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_unit'),
    sa.UniqueConstraint('name', name='uq_unit_name')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_incident_unit', 'unit', ['unit_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_unit', 'unit', ['unit_id'], ['id'])
        batch_op.drop_column('unite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unite', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_user_unit', type_='foreignkey')
        batch_op.drop_column('unit_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incident_unit', type_='foreignkey')
        batch_op.drop_column('unit_id')

    op.drop_table('unit')
    # ### end Alembic commands ###
