"""Add new fields to BilanQuotidien

Revision ID: d0034295775c
Revises: 8abb78741d41
Create Date: 2024-12-01 15:30:29.027303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0034295775c'
down_revision = '8abb78741d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilan_quotidien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dotation', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('population_totale', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('population_desservie', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('taux_desserte', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('abonnes_touches', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fuites_reparees', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('casses_reparees', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fuites_signalees', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('casses_signalees', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))
        batch_op.drop_column('nombre_abonnes_touches')
        batch_op.drop_column('nombre_casses')
        batch_op.drop_column('nombre_fuites')
        batch_op.drop_column('interventions_effectuees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilan_quotidien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interventions_effectuees', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nombre_fuites', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('nombre_casses', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('nombre_abonnes_touches', sa.INTEGER(), nullable=False))
        batch_op.drop_column('observations')
        batch_op.drop_column('casses_signalees')
        batch_op.drop_column('fuites_signalees')
        batch_op.drop_column('casses_reparees')
        batch_op.drop_column('fuites_reparees')
        batch_op.drop_column('abonnes_touches')
        batch_op.drop_column('taux_desserte')
        batch_op.drop_column('population_desservie')
        batch_op.drop_column('population_totale')
        batch_op.drop_column('dotation')

    # ### end Alembic commands ###
